version: '3.7'
services:
  db:
    cpus: "0.5"
    mem_limit: 500m
    image: postgres:15.4
    container_name: me-shop-postgres
    env_file: backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  me-backend-app:
    cpus: "1"
    mem_limit: 1000m
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: me-backend-app-dev
    env_file: backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app:cached
    command: >
      sh -c "mkdir -p /app/logs
      && touch /app/logs/logs.log
      && mkdir -p /logs
      && touch /logs/logs.log  
      && ./dev-entrypoint.sh"
    ports:
      - '8000:8000'

  me-frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: me-frontend-app-dev
    depends_on:
      - me-backend-app
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    # command: sh -c "npm run start"
    ports:
      - '3000:3000'
    restart: always

  me-frontend-partners-app:
    cpus: "0.5"
    mem_limit: 500m
    build:
      context: ./frontend_partners
      dockerfile: Dockerfile

    container_name: me-frontend-partners-app-dev
    depends_on:
      - me-backend-app
    # command: sh -c "npm run start"
    ports:
      - '3001:3000'
    restart: always

  nginx:
    cpus: "0.5"
    mem_limit: 500m
    image: nginx:1.21.3
    container_name: me-gateway-app-dev
    depends_on:
      - me-backend-app
      - me-frontend-app
    ports:
      - '80:80'
      - '8800:8800'
    volumes:
      - static_data:/staticfiles/static
      - media_data:/media
      - ./gateway/nginx.dev.conf:/etc/nginx/conf.d/default.conf
volumes:
  static_data:
  media_data:
  pg_data:
