version: '3.7'
services:
  db:
    cpus: "0.5"
    mem_limit: 500m
    image: postgres:15.4
    container_name: me-shop-postgres
    env_file: backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  me-backend-app:
    cpus: "1"
    mem_limit: 1000m
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: me-backend-app-dev
    env_file: backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app:cached
    command: sh -c "./dev-entrypoint.sh"
    ports:
      - '8000:8000'

  me-frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: me-frontend-app-dev
    depends_on:
      - me-backend-app
    volumes:
      - ./frontend:/app:cached
    command: sleep infinity
    ports:
      - '3000:3000'
    restart: always

  me-frontend-providers:
    cpus: "0.5"
    mem_limit: 500m
    build:
      context: ./providers
      dockerfile: Dockerfile

    container_name: me-frontend-providers-dev
    depends_on:
      - me-backend-app
    # command: sh -c "npm run start"
    ports:
      - '3001:3001'
    restart: always

  nginx:
    cpus: "0.5"
    mem_limit: 500m
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: me-gateway-app-dev
    depends_on:
      - me-backend-app
      - me-frontend-app
    ports:
      - '80:80'
      - '8800:8800'
    volumes:
      - static_data:/backend/var/www/api/static/
      - media_data:/backend/var/www/api/media/
    restart: always
volumes:
  static_data:
  media_data:
  pg_data:
