FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install poetry

RUN poetry config virtualenvs.create false --local

RUN poetry install

CMD ["poetry", "run", "celery", "-A", "mssite", "worker", "--loglevel=info", "--pool=solo"]