FROM python:3.10.12-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .

RUN apk update && pip install --user poetry
RUN chmod +x entrypoint.sh

ENV PATH="${PATH}:/root/.local/bin"

CMD ["poetry", "install"]
