# Generated by Django 5.0.2 on 2024-09-27 15:44

import django.db.models.deletion
import mptt.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Город доставки',
                'verbose_name_plural': 'Города доставки',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тариф доставки',
                'verbose_name_plural': 'Тарифы доставки',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки')),
                ('days_min', models.IntegerField(verbose_name='Минимальное количество дней доставки')),
                ('days_max', models.IntegerField(verbose_name='Максимальное количество дней доставки')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_components.category', verbose_name='Категория товара')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.city', verbose_name='Город')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.tariff', verbose_name='Тариф доставки')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки')),
                ('days_min', models.IntegerField(verbose_name='Минимальное количество дней доставки')),
                ('days_max', models.IntegerField(verbose_name='Максимальное количество дней доставки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.city', verbose_name='Город')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.tariff', verbose_name='Тариф доставки')),
            ],
            options={
                'verbose_name': 'Выбранная доставка',
                'verbose_name_plural': 'Выбранные доставки',
            },
        ),
        migrations.CreateModel(
            name='CityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64, verbose_name='Название города')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='delivery.city')),
            ],
            options={
                'verbose_name': 'Город доставки Translation',
                'db_table': 'delivery_city_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TariffTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64, verbose_name='Название тарифа')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='delivery.tariff')),
            ],
            options={
                'verbose_name': 'Тариф доставки Translation',
                'db_table': 'delivery_tariff_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
