# Generated by Django 5.0.2 on 2024-08-03 14:31

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_components', '0020_alter_categorytranslation_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки')),
                ('days_min', models.IntegerField(verbose_name='Минимальное кол-во дней доставки')),
                ('days_max', models.IntegerField(verbose_name='Максимальное кол-во дней доставки')),
                ('category', mptt.fields.TreeManyToManyField(to='product_components.category', verbose_name='Категория товара')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.city', verbose_name='Город')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.tariff', verbose_name='Тариф доставки')),
            ],
        ),
    ]
