# Generated by Django 5.0.2 on 2024-08-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_city_name_remove_tariff_name_citytranslation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Delivery city', 'verbose_name_plural': 'Delivery cities'},
        ),
        migrations.AlterModelOptions(
            name='citytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Delivery city Translation'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Delivery tariff', 'verbose_name_plural': 'Delivery tariffs'},
        ),
        migrations.AlterModelOptions(
            name='tarifftranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Delivery tariff Translation'},
        ),
    ]
