# Generated by Django 5.0.2 on 2024-06-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0002_images'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_components.images', verbose_name='Галерея'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
