# Generated by Django 5.0.2 on 2024-08-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0001_initial'),
        ('products', '0004_remove_product_pattern_producttranslation_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product_components.size', verbose_name='Размер'),
        ),
    ]
