# Generated by Django 5.0.2 on 2024-06-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-slug']},
        ),
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_famous',
            field=models.BooleanField(default=False, verbose_name='Популярный товар?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('UC', 'Under consideration'), ('R', 'Rejected'), ('A', 'Accepted')], default='UC', verbose_name='Статус проверки модерацией'),
        ),
    ]
