# Generated by Django 5.0.6 on 2024-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_alter_product_article_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='fifth_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Пятая картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='first_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Первая картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='fourth_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Четвертая картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Вторая картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Третья картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('UC', 'Under consideration'), ('R', 'Rejected'), ('A', 'Accepted'), ('B', 'Bin')], default='UC', verbose_name='Статус проверки модерацией'),
        ),
    ]
