# Generated by Django 5.0.2 on 2024-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcolor_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.CharField(db_index=True, max_length=9, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Bin'), ('AR', 'Archive')], default='A', verbose_name='Статус проверки модерацией'),
        ),
        migrations.AlterField(
            model_name='productstatuschangearchive',
            name='new_status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Bin'), ('AR', 'Archive')], verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='productstatuschangearchive',
            name='old_status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Bin'), ('AR', 'Archive')], verbose_name='Старый статус'),
        ),
    ]
