# Generated by Django 5.0.6 on 2024-06-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_image_product_fifth_image_and_more'),
        ('products', '0008_remove_product_is_published'),
    ]

    operations = [
    ]
