# Generated by Django 5.0.2 on 2024-09-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatuschangearchive',
            options={'verbose_name': 'Архив изменений статуса товара', 'verbose_name_plural': 'Архив изменений статуса товаров'},
        ),
    ]
