# Generated by Django 5.0.6 on 2024-06-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productstatuschangearchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstatuschangearchive',
            old_name='user',
            new_name='provider',
        ),
    ]
