# Generated by Django 5.0.2 on 2024-07-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_user_productstatuschangearchive_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatuschangearchive',
            name='new_status',
            field=models.CharField(choices=[('UC', 'Under consideration'), ('R', 'Rejected'), ('A', 'Accepted'), ('B', 'Bin')], verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='productstatuschangearchive',
            name='old_status',
            field=models.CharField(choices=[('UC', 'Under consideration'), ('R', 'Rejected'), ('A', 'Accepted'), ('B', 'Bin')], verbose_name='Старый статус'),
        ),
    ]
