# Generated by Django 5.0.2 on 2024-07-05 12:55

import providers.models
from django.db import migrations, models
import mssite


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_producttranslation_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fifth_image',
            field=models.ImageField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='', verbose_name='Пятая картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_image',
            field=models.ImageField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='', verbose_name='Первая картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='', verbose_name='Четвертая картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='', verbose_name='Вторая картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_image',
            field=models.ImageField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='', verbose_name='Третья картинка товара'),
        ),
    ]
