# Generated by Django 5.0.2 on 2024-07-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0006_delete_images'),
        ('products', '0015_alter_product_fifth_image_alter_product_first_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='product_components.color', verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product_components.size', verbose_name='Размер товара'),
        ),
    ]
