# Generated by Django 5.0.2 on 2024-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_famous',
            field=models.BooleanField(default=False),
        ),
    ]
