# Generated by Django 5.0.2 on 2024-07-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0007_image'),
        ('products', '0017_alter_product_is_famous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fifth_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fourth_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='third_image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_components.image', verbose_name='Фотографии'),
        ),
    ]
