# Generated by Django 5.0.2 on 2024-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0009_alter_producttype_name'),
        ('products', '0021_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(through='products.ProductSize', to='product_components.size', verbose_name='Размер товара'),
        ),
    ]
