# Generated by Django 5.0.2 on 2024-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес товара'),
            preserve_default=False,
        ),
    ]
