# Generated by Django 5.0.2 on 2024-07-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_producttranslation_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес товара'),
            preserve_default=False,
        ),
    ]
