# Generated by Django 5.0.2 on 2024-07-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0009_alter_producttype_name'),
        ('products', '0024_remove_producttranslation_weight_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_amount', to='product_components.size'),
        ),
    ]
