# Generated by Django 5.0.2 on 2024-07-19 08:29

import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0010_alter_productsubtype_unique_together_and_more'),
        ('products', '0025_alter_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subTypes',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='product_components.category', verbose_name='Категории товаров'),
        ),
    ]
