# Generated by Django 5.0.2 on 2024-07-19 12:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_subtypes_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='the price cannot be a negative number')], verbose_name='Цена товара'),
        ),
    ]
