# Generated by Django 5.0.2 on 2024-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_image_options_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Позиция фотографии'),
            preserve_default=False,
        ),
    ]
