# Generated by Django 5.0.2 on 2024-07-24 19:24

import mssite.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='product_images/'),
        ),
    ]
