# Generated by Django 5.0.2 on 2024-07-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
