# Generated by Django 5.0.2 on 2024-07-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0020_alter_categorytranslation_master_and_more'),
        ('products', '0034_remove_image_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество товара для выбранного цвета')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_amount', to='product_components.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(through='products.ProductColor', to='product_components.color', verbose_name='Цвет товара'),
        ),
    ]
