# Generated by Django 5.0.2 on 2024-08-16 17:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма корзины')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment', models.CharField(blank=True, max_length=16, null=True, verbose_name='Платеж')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма заказа')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('CT', 'Transferred to Cargo'), ('PR', 'Processed'), ('CD', 'Collected'), ('FD', 'Finished')], default='CR', max_length=50, verbose_name='Статус заказа')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': 'Продукты в корзинах',
                'ordering': ['amount'],
            },
        ),
    ]
