# Generated by Django 5.0.2 on 2024-08-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_remove_customer_is_verified_alter_customer_user'),
        ('delivery', '0003_alter_city_options_alter_citytranslation_options_and_more'),
        ('product_components', '0020_alter_categorytranslation_master_and_more'),
        ('products', '0039_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_components.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': 'Продукты в корзинах',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма заказа')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('PR', 'Processed'), ('CD', 'Collected'), ('FD', 'Finished')], default='CR', max_length=50, verbose_name='Статус закаказа')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.delivery', verbose_name='Тип доставки')),
                ('order_products', models.ManyToManyField(to='cart.orderproducts')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма корзины')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Покупатель оформивший заказ')),
                ('order_products', models.ManyToManyField(to='cart.orderproducts')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
