# Generated by Django 5.0.2 on 2024-06-24 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('BT', 'Bank Transfer'), ('BC', 'By card'), ('BG', 'By billing'), ('CR', 'By cryptocurrency'), ('PP', 'By PayPal service')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('CR', 'Created'), ('PR', 'Processed'), ('CD', 'Collected'), ('FD', 'Finished')], max_length=50, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='the total sum cannot be a negative number')])),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-payment_method'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Order to Product',
                'verbose_name_plural': 'Orders to Products',
                'ordering': ['amount'],
            },
        ),
    ]
