# Generated by Django 5.0.2 on 2024-08-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('customers', '0001_initial'),
        ('delivery', '0001_initial'),
        ('product_components', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.delivery', verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_components.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(to='cart.orderproducts', verbose_name='Продукты в заказе'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_products',
            field=models.ManyToManyField(to='cart.orderproducts', verbose_name='Продукты в корзине'),
        ),
    ]
