# Generated by Django 5.0.2 on 2024-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_file',
            field=models.FileField(blank=True, null=True, upload_to='check_pdf/', verbose_name='Чек об оплате заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('OP', 'On payment'), ('OI', 'On inspection'), ('CT', 'Transferred to Cargo'), ('PR', 'Processed'), ('CD', 'Collected'), ('FD', 'Finished'), ('CL', 'Closed')], default='CR', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
