# Generated by Django 5.0.2 on 2024-08-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('payment', '0003_alter_cardpayment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.cardpayment'),
        ),
    ]
