# Generated by Django 5.0.2 on 2024-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('product_components', '0002_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-payment_method']},
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.ManyToManyField(to='product_components.color'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.ManyToManyField(to='product_components.size'),
        ),
    ]
