# Generated by Django 5.0.2 on 2024-08-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card',
            new_name='payment',
        ),
    ]
