# Generated by Django 5.0.2 on 2024-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderproducts_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_products',
            field=models.ManyToManyField(related_name='carts', to='cart.orderproducts', verbose_name='Продукты в корзине'),
        ),
    ]
