# Generated by Django 5.0.2 on 2024-07-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_address_alter_order_created_date_and_more'),
        ('product_components', '0006_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(to='cart.orderproduct'),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_components.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_components.size'),
            preserve_default=False,
        ),
    ]
