# Generated by Django 5.0.2 on 2024-08-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_order_products'),
        ('product_components', '0001_initial'),
        ('products', '0007_alter_productcolor_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_components.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Продукт'),
        ),
    ]
