# Generated by Django 5.0.2 on 2024-07-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_orderproduct_date_remove_orderproduct_order_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Покупатель оформивший заказ'),
            preserve_default=False,
        ),
    ]
