# Generated by Django 5.0.2 on 2024-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PR', 'Processed'), ('CD', 'Collected'), ('FD', 'Finished')], default='CR', max_length=50, verbose_name='Статус закаказа'),
        ),
    ]
