# Generated by Django 5.0.2 on 2024-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BT', 'Bank Transfer'), ('BC', 'By card'), ('BG', 'By billing'), ('CR', 'By cryptocurrency'), ('PP', 'By PayPal service')], default='BC', max_length=50, verbose_name='Метод оплаты заказа'),
        ),
    ]
