# Generated by Django 5.0.2 on 2024-07-19 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_created_date_alter_order_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='sum',
            field=models.FloatField(default=0, verbose_name='Сумма позиции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='the total sum cannot be a negative number')], verbose_name='Общая сумма заказа'),
        ),
    ]
