# Generated by Django 5.0.2 on 2024-07-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_orderproduct_sum_alter_order_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='sum',
        ),
    ]
