# Generated by Django 5.0.2 on 2024-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_orderproduct_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
