# Generated by Django 5.0.2 on 2024-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_orderproduct_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма заказа'),
        ),
    ]
