# Generated by Django 5.0.2 on 2024-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_order_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CR', 'Created'), ('PR', 'Processed'), ('CD', 'Collected'), ('FD', 'Finished')], max_length=50, null=True, verbose_name='Статус закаказа'),
        ),
    ]
