# Generated by Django 5.0.2 on 2024-07-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_order_options_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='max_delivery_period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Максимальный период доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='min_delivery_period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Минимальный период доставки'),
        ),
    ]
