# Generated by Django 5.0.2 on 2024-07-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_city_order_max_delivery_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
