# Generated by Django 5.0.2 on 2024-06-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
