# Generated by Django 5.0.2 on 2024-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0003_alter_productsubtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_hex',
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
