# Generated by Django 5.0.2 on 2024-06-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0004_rename_color_color_color_hex_alter_color_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_hex',
            new_name='color',
        ),
    ]
