# Generated by Django 5.0.6 on 2024-06-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0005_rename_color_hex_color_color'),
        ('products', '0007_remove_product_image_product_fifth_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
