# Generated by Django 5.0.2 on 2024-07-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0007_image'),
        ('products', '0019_remove_product_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
