# Generated by Django 5.0.2 on 2024-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0008_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
