# Generated by Django 5.0.2 on 2024-07-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0010_alter_productsubtype_unique_together_and_more'),
        ('products', '0026_remove_product_subtypes_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSubType',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
