# Generated by Django 5.0.2 on 2024-07-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0011_delete_productsubtype_delete_producttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
    ]
