# Generated by Django 5.0.2 on 2024-07-19 19:00

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0013_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='product_components.category')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
    ]
