# Generated by Django 5.0.2 on 2024-07-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0014_producttranslation_delete_categorytranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTranslation',
            new_name='CategoryTranslation',
        ),
    ]
