# Generated by Django 5.0.2 on 2024-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0017_alter_color_options_remove_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024, unique=True, verbose_name='Слаг цвета'),
        ),
    ]
