# Generated by Django 5.0.2 on 2024-07-20 10:47

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0018_color_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturercountry',
            options={'verbose_name': 'Product manufacturer country', 'verbose_name_plural': 'Product manufacturer countries'},
        ),
        migrations.RemoveField(
            model_name='manufacturercountry',
            name='name',
        ),
        migrations.AddField(
            model_name='manufacturercountry',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024, unique=True, verbose_name='Слаг страны производителя'),
        ),
        migrations.CreateModel(
            name='ManufacturerCountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='product_components.manufacturercountry')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
