# Generated by Django 5.0.2 on 2024-07-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_components', '0019_alter_manufacturercountry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product_components.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colortranslation',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product_components.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturercountrytranslation',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product_components.manufacturercountry'),
            preserve_default=False,
        ),
    ]
