# Generated by Django 5.0.2 on 2024-09-27 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mssite.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=34, verbose_name='Номер банковского счета')),
            ],
            options={
                'verbose_name': 'Номер банковского счета',
                'verbose_name_plural': 'Номера банковских счетов',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('country', models.CharField(max_length=20, verbose_name='Страна поставщика')),
                ('company', models.CharField(max_length=2048, verbose_name='Название компании')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('taxpayer_identification_number', models.CharField(max_length=20, unique=True, verbose_name='ИНН или его аналог')),
                ('state', models.CharField(choices=[('M', 'Moderating'), ('B', 'Blocked'), ('F', 'Finished'), ('C', 'Canceled')], default='M', max_length=50, verbose_name='Состояние')),
                ('last_downloaded_file', models.FileField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='downloaded_xlsx/', verbose_name='Последний загруженный файл')),
                ('bank_account_number', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='providers.bankaccountnumber', verbose_name='Номер банковского счета')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
