# Generated by Django 5.0.2 on 2024-06-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=20, verbose_name='Страна поставщика')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона поставшика')),
                ('company', models.CharField(max_length=2048, verbose_name='Название компании')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('taxpayer_identification_number', models.CharField(unique=True, verbose_name='ИНН или его аналог')),
                ('state', models.CharField(choices=[('M', 'Moderating'), ('B', 'Blocked'), ('F', 'Finished'), ('C', 'Canceled')], max_length=50)),
                ('bank_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.bankaccountnumber', verbose_name='Номера банковских счетов')),
            ],
        ),
    ]
