# Generated by Django 5.0.2 on 2024-06-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='downloaded_xlsx/'),
        ),
    ]
