# Generated by Django 5.0.2 on 2024-08-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_bankaccountnumber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccountnumber',
            options={'verbose_name': 'Номер банковского счета', 'verbose_name_plural': 'Номера банковских счетов'},
        ),
        migrations.AddField(
            model_name='bankaccountnumber',
            name='number',
            field=models.CharField(default=1, max_length=34, verbose_name='Номер банковского счета'),
            preserve_default=False,
        ),
    ]
