# Generated by Django 5.0.2 on 2024-06-27 16:56

import providers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_last_downloaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_downloaded_file',
            field=models.FileField(blank=True, null=True, storage=providers.models.OverwriteStorage(), upload_to='downloaded_xlsx/'),
        ),
    ]
