# Generated by Django 5.0.2 on 2024-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_provider_last_downloaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона поставщика'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(choices=[('M', 'Moderating'), ('B', 'Blocked'), ('F', 'Finished'), ('C', 'Canceled')], default='M', max_length=50),
        ),
    ]
