# Generated by Django 5.0.2 on 2024-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
