# Generated by Django 5.0.2 on 2024-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_provider_phone_number_alter_provider_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='downloaded_xlsx/'),
        ),
    ]
