# Generated by Django 5.0.2 on 2024-08-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bank_account_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='providers.bankaccountnumber', verbose_name='Номер банковского счета'),
        ),
    ]
