# Generated by Django 5.0.2 on 2024-07-13 16:44

import mssite
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_alter_provider_last_downloaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_downloaded_file',
            field=models.FileField(blank=True, null=True, storage=mssite.storages.OverwriteStorage(), upload_to='downloaded_xlsx/'),
        ),
    ]
