# Generated by Django 5.0.2 on 2024-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_provider_last_downloaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона поставщика'),
        ),
    ]
