# Generated by Django 5.0.2 on 2024-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_alter_provider_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Является ли поставщик верифицированным'),
        ),
    ]
