# Generated by Django 5.0.2 on 2024-08-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_provider_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='phone_number',
        ),
    ]
