# Generated by Django 5.0.2 on 2024-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='card',
            name='expiration_month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='expiration_year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='payment_system',
            field=models.CharField(choices=[('1', 'Visa'), ('2', 'MasterCard')], default=1),
            preserve_default=False,
        ),
    ]
