# Generated by Django 5.0.2 on 2024-08-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('providers', '0006_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='upcoming_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ожидаемый баланс'),
        ),
    ]
