# Generated by Django 5.0.2 on 2024-07-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_review_options_alter_review_unique_together'),
        ('payment', '0002_remove_card_expiration_date_card_expiration_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer'),
        ),
    ]
