# Generated by Django 5.0.2 on 2024-08-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_wallet_balance_alter_wallet_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='created',
            new_name='created_datetime',
        ),
    ]
