# Generated by Django 5.0.2 on 2024-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_verified_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Номер телефона'),
        ),
    ]
