# Generated by Django 5.0.2 on 2024-08-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appeal',
        ),
    ]
