name: Development workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

env:
  NEXT_PUBLIC_URL: https://turanline.com

jobs:
  changes:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      gateway: ${{ steps.changes.outputs.gateway }}
      frontend_partners: ${{ steps.changes.outputs.frontend_partners }}
      frontend_cargo: ${{ steps.changes.outputs.frontend_cargo }}
      frontend_admin: ${{ steps.changes.outputs.frontend_admin }}
      frontend_warehouse: ${{ steps.changes.outputs.frontend_warehouse }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        base: ${{ github.ref_name }}
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
          gateway:
            - 'gateway/**'
          frontend_cargo:
            - 'frontend_cargo/**'
          frontend_partners:
            - 'frontend_partners/**'
          frontend_admin:
            - 'frontend_admin/**'
          frontend_warehouse:
            - 'frontend_warehouse/**'

  # tests:
  #   name: PEP8 check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.8
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip 
  #         pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
  #         cd backend/
  #         pip install -r requirements.txt
  #     - name: Test with flake8
  #       run: |
  #         python -m flake8 backend

  backend_build_and_push:
    name: Build And Push Backend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_backend:latest

  frontend_build_and_push:
    name: Build And Push Frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend:latest

  partners_build_and_push:
    name: Build And Push Frontend Partners Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_partners == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_partners/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_partners/
          push: true
          file: ./frontend_partners/Dockerfile.prod
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_partners:latest

  cargo_build_and_push:
    name: Build And Push Cargo Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_cargo == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_cargo/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_cargo/
          push: true
          file: ./frontend_cargo/Dockerfile.prod
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_cargo:latest

  admin_build_and_push:
    name: Build And Push Admin Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_admin == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_admin/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_admin/
          push: true
          file: ./frontend_admin/Dockerfile.prod
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_admin:latest
          
  warehouse_build_and_push:
    name: Build And Push Warehouse Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_warehouse == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_warehouse/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_warehouse/
          push: true
          file: ./frontend_warehouse/Dockerfile.prod
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_warehouse:latest

  gateway_build_and_push:
    name: Push gateway Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.gateway == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./gateway/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_gateway:latest
          build-args: |
            - NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}

  # deploy:
  #   name: Deploying on remote server
  #   runs-on: ubuntu-latest
  #   needs:
  #     - changes
  #     - backend_build_and_push
  #     - frontend_build_and_push
  #     - gateway_build_and_push
  #     - cargo_build_and_push
  #     - admin_build_and_push
  #     - warehouse_build_and_push
  #     - partners_build_and_push
  #   if: |
  #     needs.changes.result == 'success' &&
  #     (needs.backend_build_and_push.result == 'success' || needs.backend_build_and_push.result == 'skipped') &&
  #     (needs.frontend_build_and_push.result == 'success' || needs.frontend_build_and_push.result == 'skipped') &&
  #     (needs.gateway_build_and_push.result == 'success' || needs.gateway_build_and_push.result == 'skipped') &&
  #     (needs.cargo_build_and_push.result == 'success' || needs.cargo_build_and_push.result == 'skipped') &&
  #     (needs.admin_build_and_push.result == 'success' || needs.admin_build_and_push.result == 'skipped') &&
  #     (needs.warehouse_build_and_push.result == 'success' || needs.warehouse_build_and_push.result == 'skipped') &&
  #     (needs.partners_build_and_push.result == 'success' || needs.partners_build_and_push.result == 'skipped')
  #   steps:
  #   - name: Checkout repo
  #     uses: actions/checkout@v4
  #   - name: Copy docker-compose.yml via ssh
  #     uses: appleboy/scp-action@master
  #     with:
  #       host: ${{ secrets.PROD_HOST }}
  #       username: ${{ secrets.PROD_USER }}
  #       password: ${{ secrets.PROD_PASSWORD }}
  #       source: "docker-compose.test.yml, nginx.test.conf"
  #       target: "turanline"
  #   - name: Executing remote ssh commands to deploy
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.PROD_HOST }}
  #       username: ${{ secrets.PROD_USER }}
  #       password: ${{ secrets.PROD_PASSWORD }}
  #       script: |
  #         cd turanline
  #         sudo docker compose -f docker-compose.prod.yml pull
  #         sudo docker compose -f docker-compose.prod.yml down
  #         sudo docker compose -f docker-compose.prod.yml up -d

# sudo docker compose -f docker-compose.test.yml exec backend python manage.py migrate
# sudo docker compose -f docker-compose.test.yml exec backend python manage.py collectstatic --no-input
# sudo docker compose -f docker-compose.test.yml exec backend cp -r /app/collected_static/. /backend_static/static/

  # send_message:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #   - name: Send message
  #     uses: appleboy/telegram-action@master
  #     with:
  #       to: ${{ secrets.TELEGRAM_TO }}
  #       token: ${{ secrets.TELEGRAM_TOKEN }}
  #       message: Деплой foodgram успешно выполнен! Коммит сделал ${{ github.actor }} с сообщением "${{ github.event.commits[0].message }}". Ссылка на коммит https://github.com/${{ github.repository }}/commit/${{github.sha}}.