name: Development workflow

on:
  push:
    branches: [ workflowtest ]
    paths-ignore:
      - '**/README.md'

env:
  NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      gateway: ${{ steps.changes.outputs.gateway }}
      frontend_partners: ${{ steps.changes.outputs.frontend_partners }}
      frontend_cargo: ${{ steps.changes.outputs.frontend_cargo }}
      frontend_admin: ${{ steps.changes.outputs.frontend_admin }}
      frontend_warehouse: ${{ steps.changes.outputs.frontend_warehouse }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        base: ${{ github.ref_name }}
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
          gateway:
            - 'gateway/**'
          frontend_cargo:
            - 'frontend_cargo/**'
          frontend_partners:
            - 'frontend_partners/**'
          frontend_admin:
            - 'frontend_admin/**'
          frontend_warehouse:
            - 'frontend_warehouse/**'

  # tests:
  #   name: PEP8 check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.8
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip 
  #         pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
  #         cd backend/
  #         pip install -r requirements.txt
  #     - name: Test with flake8
  #       run: |
  #         python -m flake8 backend

  backend_build_and_push:
    name: Build And Push Backend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_backend_dev:latest

  frontend_build_and_push:
    name: Build And Push Frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_dev:latest

  partners_build_and_push:
    name: Build And Push Frontend Partners Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_partners == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_partners/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_partners/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_partners_dev:latest

  cargo_build_and_push:
    name: Build And Push Cargo Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_cargo == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_cargo/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_cargo/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_cargo_dev:latest

  admin_build_and_push:
    name: Build And Push Admin Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_admin == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_admin/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_admin/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_admin_dev:latest
          
  warehouse_build_and_push:
    name: Build And Push Admin Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend_warehouse == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          NEXT_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_URL }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}" > ./frontend_warehouse/.env

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_warehouse/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_frontend_warehouse_dev:latest

  gateway_build_and_push:
    name: Push gateway Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.gateway == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./gateway/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turanline_gateway_dev:latest
          build-args: |
            - NEXT_PUBLIC_URL=${{ env.NEXT_PUBLIC_URL }}

  deploy:
    name: Deploying on remote server
    runs-on: ubuntu-latest
    needs:
      - backend_build_and_push
      - frontend_build_and_push
      - gateway_build_and_push
      - cargo_build_and_push
      - admin_build_and_push
      - warehouse_build_and_push
      - partners_build_and_push
    if: |
      always() && 
      (needs.backend_build_and_push.result == 'success' || needs.backend_build_and_push.result == 'skipped') &&
      (needs.frontend_build_and_push.result == 'success' || needs.frontend_build_and_push.result == 'skipped') &&
      (needs.gateway_build_and_push.result == 'success' || needs.gateway_build_and_push.result == 'skipped') &&
      (needs.cargo_build_and_push.result == 'success' || needs.cargo_build_and_push.result == 'skipped') &&
      (needs.admin_build_and_push.result == 'success' || needs.admin_build_and_push.result == 'skipped') &&
      (needs.warehouse_build_and_push.result == 'success' || needs.warehouse_build_and_push.result == 'skipped') &&
      (needs.partners_build_and_push.result == 'success' || needs.partners_build_and_push.result == 'skipped')
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Copy docker-compose.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        password: ${{ secrets.TEST_PASSWORD }}
        source: "docker-compose.test.yml, nginx.test.conf"
        target: "turanline_dev"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        password: ${{ secrets.TEST_PASSWORD }}
        script: |
          cd turanline_dev
          sudo docker compose -f docker-compose.test.yml pull
          sudo docker compose -f docker-compose.test.yml down
          sudo docker compose -f docker-compose.test.yml up -d

# sudo docker compose -f docker-compose.test.yml exec backend python manage.py migrate
# sudo docker compose -f docker-compose.test.yml exec backend python manage.py collectstatic --no-input
# sudo docker compose -f docker-compose.test.yml exec backend cp -r /app/collected_static/. /backend_static/static/

  # send_message:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #   - name: Send message
  #     uses: appleboy/telegram-action@master
  #     with:
  #       to: ${{ secrets.TELEGRAM_TO }}
  #       token: ${{ secrets.TELEGRAM_TOKEN }}
  #       message: Деплой foodgram успешно выполнен! Коммит сделал ${{ github.actor }} с сообщением "${{ github.event.commits[0].message }}". Ссылка на коммит https://github.com/${{ github.repository }}/commit/${{github.sha}}.